C
C****************************  ABSTRACT  *****************************
C
C     THIS PROGRAM USES A 4TH ORDER RUNGE-KUTTA METHOD TO INTEGRATE A
C  SYSTEM OF FIRST ORDER ODE'S.  THE USER SUPPLIES THE INITIAL CONDITIONS
C  AND THE FINAL VALUE OF X, AS WELL AS THE EQUATIONS FOR F(X,Y).  THIS
C  PROGRAM USES A STEP SIZE REGULATOR SO THAT THE STEP SIZE DX RESULTS IN
C  A MAXIMUM FRACTIONAL CHANGE IN ANY Y.
C
C****************************  NOMENCLATURE  *************************
C
C  DXPNT- THE PRINT INTERVAL
C  FUNCT- THE NAME OF THE SUBROUTINE THAT CALCULATES F(X,Y)
C  IPNT- PRINT FLAG (=0 NO PRINT; =1 PRINT)
C  N- THE NUMBER OF DEPENDENT VARIABLES
C  P- THE MAXIMUM PERCENTAGE CHANGE OF ANY Y(I)
C  X- THE INDEPENDENT VARIABLE
C  XMAX-  THE FINAL VALUE OF X
C  Y-  THE ITH DEPENDENT VARIABLE
C
C************************************************************************
C
C
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION Y(2),DYDX(2),CAY(2),Y1(2)
C  EXTERNAL STATEMENT FOR DERIVATIVE SUBROUTINE
      EXTERNAL FUNCT
C  SPECIFY INPUT DATA
      X=0.0
      N=2
      Y(1)=1.0
      Y(2)=300.
      XMAX=100.
      P=13.
      DXPNT=10.
      IPNT=1
C  CALL RUNGE-KUTTA METHOD
      CALL RKUTTA(FUNCT,N,P,X,Y,XMAX,DXPNT,IPNT,CAY,Y1,DYDX)
      STOP
      END
C
C*****************************  ABSTRACT  *****************************
C
C     THIS SUBROUTINE CALLS SUBROUTINE RK1 AT EACH PRINT INTERVAL
C  AND PRINTS OUT THE INTERMEDIATE RESULTS IF IPNT=1.
C
C****************************  NOMENCLATURE  **************************
C
C  DXPNT- THE PRINT INTERVAL
C  DXP- THE INTERNALLY CALCULATED PRINT INTERVAL
C  F- THE NAME OF THE SUBROUTINE THAT CALCULATES F(X,Y)
C  IPNT- PRINT FLAG (=0 NO PRINT; =1 PRINT)
C  N- THE NUMBER OF DEPENDENT VARIABLES
C  NS- THE NUMBER OF PRINT INTERVAL STEPS
C  PRO- THE PRINT INTERVAL NEAR XMAX
C  X- THE INDEPENDENT VARIABLE
C  XF- THE VALUE OF X AT THE END OF THE PRINT INTERVAL
C  XO- THE VALUE OF X AT THE BEGINNING OF THE PRINT INTERVAL
C  XMAX-  THE FINAL VALUE OF X
C  Y(I)-  THE ITH DEPENDENT VARIABLE
C
C**********************************************************************
C
      SUBROUTINE RKUTTA(F,N,P,X,Y,XMAX,DXPNT,IPNT,CAY,Y1,DYDX)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION Y(1),DYDX(1),CAY(1),Y1(1)
      EXTERNAL F
C  PRINT INITIAL CONDITIONS IF IPNT = 1
      IF(IPNT.EQ.1)WRITE(6,10)X,(Y(J),J=1,N)
C  CALCULATE THE NUMBER OF STEPS PER DXPNT
      DXP=DXPNT
      NS=IFIX(XMAX/DXPNT)+1
      XO=X
      PRO=XMAX-DXPNT*DFLOAT(NS-1)
C
C  CALL SUBROUTINE RK TIL X=XMAX
C
      DO 1000 I=1,NS
      IF(I.EQ.NS)DXP=PRO
      IF((I.EQ.NS).AND.(PRO.LT.1.E-6))GO TO 1000
      XF=XO+DXP
C  CALL SUBROUTINE RK
      CALL RK(F,N,P,XO,XF,Y,CAY,Y1,DYDX)
C  PRINT INTERMEDIATE RESULTS IF IPNT=1
      IF(IPNT.EQ.1)WRITE(6,10)XF,(Y(J),J=1,N)
   10 FORMAT( 10X,3H X=,D12.5,3X,3H Y=,5(D14.7,3X))
C  INCREMENT X
 1000 XO=XO+DXP
      RETURN
      END
C
C*************************  ABSTRACT  ********************************
C
C     THIS APPLIES A FOURTH ORDER RUNGE-KUTTA METHOD FOR THE INTEGRATION
C  OF A SYSTEM OF ODE'S FROM X=XO TO X=XF.
C
C****************************  NOMENCLATURE  **************************
C
C  CAY(I)- A VECTOR USED TO STORE THE SLOPES OF DEPENDENT VARIABLE I
C	   AT THE BEGINNING, MIDDLE AND END OF A STEP DX
C  DX- THE STEP SIZE FOR X
X  DXM- THE MINIMUM STEP SIZE DX
C  DYDX(I)- THE DERIVATIVE OF Y(I) WITH RESPECT TO X
C  F- THE NAME OF THE SUBROUTINE THAT CALCULATES F(X,Y)
C  IPNT- PRINT FLAG (=0 NO PRINT; =1 PRINT)
C  N- THE NUMBER OF DEPENDENT VARIABLES
C  NS- THE NUMBER OF PRINT INTERVAL STEPS
C  PRO- THE PRINT INTERVAL NEAR XMAX
C  X- THE INDEPENDENT VARIABLE
C  XF- THE VALUE OF X AT THE END OF THE PRINT INTERVAL
C  XO- THE VALUE OF X AT THE BEGINNING OF THE PRINT INTERVAL
C  Y(I)- THE ITH DEPENDENT VARIABLE
C  Y1(I)- AN INTERNALLY USED VALUE OF THE ITH DEPENDENT VARIABLE
C
C**********************************************************************
C
      SUBROUTINE RK(F,N,P,XO,XF,Y,CAY,Y1,DYDX)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION Y(1),DYDX(1),CAY(1),Y1(1)
      EXTERNAL F
      X=XO
C
C  BEGIN ITERATIVE CALCULATION LOOP
C
    1 CALL F(N,X,Y,DYDX)
C
C  STEP SIZE CALCULATION
C
      DDD=DYDX(1)
      IF(DABS(DYDX(1)).LT.1.E-10)DDD=1.E-10
      DXM=DABS(P*Y(1)/DDD/100.)
C  DETERMINE THE MINIMUM STEP SIZE DX BASED UPON A P% CHANGE
      DO 2 I=2,N
      IF(DYDX(I).LT.1.E-10)GO TO 2
      TEST=DABS(P*Y(I)/DYDX(I)/100.)
      IF(TEST.LT.DXM)DXM=TEST
    2 CONTINUE
C  MAKE SURE THAT X DOES NOT EXCEED XF
      IF(DXM.LT.1.E-4)DXM=1.E-4
      DX=DXM
      XT=X+DX
      IF(XT.GT.XF)DX=XF-X
C  SET K1
      DO 33 I=1,N
      CAY(I)=DYDX(I)
   33 Y1(I)=Y(I)+DYDX(I)*DX/2.
      X1=X+DX/2.
      CALL F(N,X1,Y1,DYDX)
C  SET K2
      DO 34 I=1,N
      CAY(I)=CAY(I)+2.*DYDX(I)
   34 Y1(I)=Y(I)+DYDX(I)*DX/2.
      CALL F(N,X1,Y1,DYDX)
C  SET K3
      DO 35 I=1,N
      CAY(I)=CAY(I)+2.*DYDX(I)
   35 Y1(I)=Y(I)+DYDX(I)*DX
      X1=X+DX
      CALL F(N,X1,Y1,DYDX)
C  SET K4 AND CALCULATE NEW VALUES OF Y(I)
      DO 36 I=1,N
      CAY(I)=CAY(I)+DYDX(I)
   36 Y(I)=Y(I)+DX*CAY(I)/6.
C  INCREMENT X
  100 X=X+DX
      IF(X.LT.XF)GO TO 1
      RETURN
      END
C
C*************************  ABSTRACT  ********************************
C
C     THIS SUBROUTINE CALCULATES THE DERIVATIVE OF Y(I) WITH RESPECT TO
C  X, DYDX(I).  THE USER SUPPLIES THE EQUATIONS FOR DYDX(I).
C
C*********************************************************************
C
C
      SUBROUTINE FUNCT(N,X,Y,DYDX)
      DOUBLE PRECISION X,Y(2),DYDX(2)
      DYDX(1)=-.1*Y(1)*DEXP(-300/Y(2))
      DYDX(2)= 1.*Y(1)*DEXP(-300/Y(2))
      RETURN
      END
