C
C**************************  ABSTRACT  **********************************
C
C     THIS SUBROUTINE SOLVES A SET OF LINEAR EQUATIONS USING THE GAUSS-
C  SEIDEL METHOD.
C
C**************************  NOMENCLATURE  ******************************
C
C  A(I,J)-  THE COEFFICIENT OF THE JTH VARIABLE IN THE ITH EQUATION
C  B(I)-  THE CONSTANT TERM FOR THE ITH EQUATION
C  DIA-  THE VALUE OF THE DIAGONAL ELEMENT
C  DXMAX- MAXIMUM ERROR
C  ERLIM- THE ERROR CRITERIA
C  ITER-  THE ITERATION COUNTER
C  ITMAX- THE MAXIMUM NUMBER OF ITERATIONS
C  N-  THE NUMBER OF LINEAR EQUATIONS
C  X(I)-  THE VECTOR CONTAINING THE SOLUTION
C
C************************************************************************
C
C
      SUBROUTINE GAUSID(N,A,B,X,ERLIM,ITMAX)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION A(N,1),B(1),X(1)
C
C  NORMALIZE EACH EQUATION WITH ITS DIAGONAL ELEMENT
C
      DO 1 I=1,N
      DIA=A(I,I)
      B(I)=B(I)/DIA
      DO 2 J=1,N
    2 A(I,J)=A(I,J)/DIA
    1 CONTINUE
C
C  BEGIN THE ITERATION PROCESS
C
      ITER=0
  100 ITER=ITER+1
      DXMAX=0.0
      DO 3 I=1,N
      DIA=X(I)
      X(I)=B(I)
C  APPLY THE GAUSS-SEIDEL APPROXIMATION TO EACH EQUATION
      DO 4 J=1,N
    4 IF(J.NE.I)X(I)=X(I)-A(I,J)*X(J)
    3 IF(DABS(X(I)-DIA).GT.DXMAX)DXMAX=DABS(X(I)-DIA)
      IF(ITER.GT.ITMAX)GO TO 5
C
C  CHECH FOR CONVERGENCE
C
      IF(DXMAX.GT.ERLIM)GO TO 100
C
C  PRINT OUT NUMBER OF ITERATIONS AND DXMAX
C
      WRITE(6,81)
   81 FORMAT( 10X,30H GAUSS-SEIDEL METHOD CONVERGED)
      WRITE(6,55)ITER,DXMAX
   55 FORMAT( 10X,6H ITER=,I6,5X,4H DX=,D14.7)
      RETURN
    5 WRITE(6,6)DXMAX
    6 FORMAT( 44H GAUSS-SEIDEL METHOD DID NOT CONVERGE DXMAX=,D14.7)
      RETURN
      END
