C
C***************************  ABSTRACT  *********************************
C
C     THIS SUBROUTINE PERFORMS A MULTIPLE LINEAR REGRESSION UPON A SET
C  OF DATA THAT IS SUPPOSED TO BE REPRESENTED BY A LINEAR RELATIONSHIP.
C  THE VALUES OF THE INDEPENDENT VARIABLES ARE PASSED  AS X(J,I) FOR THE
C  JTH VARIABLE IN THE ITH SET OF DATA AND Y(I) IS THE CONSTANT TERM.
C
C**************************  NOMENCALTURE  ******************************
C
C  A(I)-  THE RESULTING REGRESSION COEFICIENTS
C  B(I)-  THE CONSTANT TERM IN THE SET OF LINEAR EQUATIONS
C  C(I,I)-  THE COEFICIENT MATRIX OF THE SET OF LINEAR EQUATIONS
C  M-  THE NUMBER OF UNKNOWN COEFICIENTS
C  N-  THE NUMBER OF DATA POINTS
C  SXY-  THE STANDARD ERROR OF THE REGRESSION
C  X(J,I)-  THE VALUE OF THE JTH COEFICIENT IN THE ITH SET OF DATA
C  Y(I)-  THE CONSTANT TERM IN THE ITH SET OF DATA
C
C************************************************************************
C
      SUBROUTINE MLR(N,M,X,Y,A,SXY,C,B,IPVT)
      IMPLICIT REAL*8(A-H,O-Z)
      DIMENSION C(M,1),B(1),A(1),IPVT(1),X(M,1),Y(1)
C
C  CHECK TO SEE THAT THERE IS ENOUGH DATA PROVIDED
C
      IF(N.LE.(M+1))WRITE(6,22)
   22 FORMAT( 34H THERE IS NOT ENOUGH DATA PROVIDED)
      IF(N.LE.(M+1))RETURN
C
C  CALCULATE THE COEFICIENTS OF THE SYSTEM OF LINEAR EQUATIONS
C
      DO 1 J=1,M
      DO 1 K=1,M
      SUM=0.0
      DO 2 I=1,N
    2 SUM=SUM+X(J,I)*X(K,I)
    1 C(J,K)=SUM
C
C  CALCULATE THE CONSTANT TERM IN THE SYSTEM OF LINEAR EQUATIONS
C
      DO 3 J=1,M
      SUM=0.0
      DO 4 I=1,N
    4 SUM=SUM+X(J,I)*Y(I)
    3 B(J)=SUM
C
C   CALL LINEAR EQUATION SOLVER
C
      CALL LINPAC(M,C,B,A,IPVT)
C
C   CALCULATE THE STANDARD ERROR OF THE REGRESSION
C
      S=0.0
      DO 10 I=1,N
      SUM=0.0
      DO 11 J=1,M
   11 SUM=SUM+A(J)*X(J,I)
   10 S=S+(Y(I)-SUM)**2
      SXY=DSQRT(S/(FLOAT(N-M-1)))
C
C  PRINT OUT RESULTS
C
      WRITE(6,83)
   83 FORMAT( ///)
      WRITE(6,84)
   84 FORMAT( 51H THE RESULTS OF THE MULTIPLE LINEAR REGRESSION ARE:)
      DO 88 I=1,M
   88 WRITE(6,89)I,A(I)
   89 FORMAT( 10X,3H A(,I1,3H)= ,D14.7)
      WRITE(6,85)SXY
   85 FORMAT( 10X,40H THE STANDARD ERROR OF THE REGRESSION = ,D14.7)
      RETURN
      END
