C
C*****************************  ABSTRACT  *******************************
C
C     THIS SUBROUTINE APPLIES THE METHOD OF SUCCESSIVE SUBSTITUITION FOR
C  FOR THE SOLUTION OF A SINGLE NONLINEAR EQUATION.
C
C****************************  NOMENCLATURE  ****************************
C
C  ERLIM- CONVERGENCE CRITERIA
C  FX- THE FUNCTION VALUE
C  IC- THE ITERATION COUNTER
C  ICMAX- THE MAXIMUM NUMBER OF ITERATIONS ALLOWED
C  IPRINT- PRINT FLAG =1 PRINT INTERMEDIATE VALUE; =0 NO PRINT
C  X-  THE INITIAL GUESS FOR THE ROOT (INPUT); THE SOLUTION VALUE OF
C      X (OUTPUT)
C  XS- VARIABLE USED TO SAVE THE OLD VALUE OF X
C
C************************************************************************
C
      SUBROUTINE SUCSUB(G,ERLIM,ICMAX,IPRINT,X)
      IMPLICIT REAL*8(A-H,O-Z)
      EXTERNAL G
      IC=0
C
C  BEGIN ITERATIVE LOOP
C
   10 IC=IC+1
C  SAVE CURRENT VALUE OF X
      XS=X
C  CALL SUBROUTINE G(X)
      CALL G(X)
C  EVALUATE FUNCTION VALUE
      FX=X-XS
C  PRINT OUT INTERMEDIATE RESULTS
      IF(IPRINT.EQ.1)WRITE(6,11)IC,X,FX
   11 FORMAT( 5X,' IC=',I3,5X,' X=',D10.3,5X,' F(X)=',D10.3)
C  CHECK FOR EXCESSIVE ITERATIONS
      IF(IC.GT.ICMAX)WRITE(6,22)
   22 FORMAT( ' SUCCESSIVE SUBSTITUTION ALGORITHM DID NOT CONVERGE')
      IF(IC.GT.ICMAX)STOP
C  CHECK FOR CONVERGENCE
      IF(DABS(FX).GT.ERLIM)GO TO 10
C
C  CONVERGED SOLUTION OBTAINED; RETURNING TO CALLING PROGRAM
C
      RETURN
      END
